### ISSUE TITLE
How to restore wallet?

### ISSUE THREAD

**Issue by qwertyuu** [SaltineChips/Konjungate#1]
There were a corruption in my wallet, what should I do to restore it? I could not launch the executable but I still had the .dat and backups in the data folders.

Thanks!

**Comment by SaltineChips** [comment]
if windows os:
close CampusCash.exe
navigate to %appdata%/KONJ, delete everything **except** for your wallet.dat, Konjungate.conf, and peers.dat
After this re-open your wallet, if it still doesn't work export your privkey to a secure location, then import it later.
if linux os:
do the following commands:
ls -la, confirm if you have Konjungate
Konjungated stop
cd ~/.KONJ;
ls -la
rm -rf backups; rm -r blk0001.dat; rm -r blocks; rm -r database; rm -r db.log; rm -r debug.log; rm -r .lock; rm -r mncache.dat; rm -r smsgDB; rm -r smsg.ini; rm -r txleveldb
cd ~
Konjungated

Please let me know if this still doesn't work. Please git clone from https://github.com/SaltineChips/Konjungate-Control and not from this repo, as it is experimental and meant to fork.
